openapi: 3.0.0
info:
  description: "A test server for managing user profiles."
  version: "1.0.0"
  title: "User Profile API"
paths:
  /profile:
    get:
      summary: "Get user profiles"
      description: "Returns a list of user profiles or a specific user profile if a username is provided."
      operationId: "getProfile"
      parameters:
        - name: "Api-key"
          in: "header"
          required: true
          schema:
            type: "string"
          description: "API key for authorization"
        - name: "username"
          in: "query"
          required: false
          schema:
            type: "string"
          description: "Username find the profile"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/UserProfile"
                  - type: "array"
                    items:
                      $ref: "#/components/schemas/UserProfile"
        '400':
          description: "Invalid username"
        '401':
          description: "Unauthorized"
        '403':
          description: "Forbidden"
        '404':
          description: "User profile not found"
        '500':
          description: "Internal server error"
components:
  schemas:
    UserProfile:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        username:
          type: "string"
        first_name:
          type: "string"
        last_name:
          type: "string"
        phone:
          type: "string"
        address:
          type: "string"
        city:
          type: "string"
        school:
          type: "string"
      required:
        - id
        - username
        - first_name
        - last_name
        - phone
        - address
        - city
        - school